### PR TITLE
contributing: use documented -S instead of -H

### PR DESCRIPTION
**Pull request by julianoes**
`-H` is an undocumented cmake flag that we should not rely upon.

See: https://stackoverflow.com/a/54279862/8548472

### CODE REVIEW

**Comment by JonasVautherin** [comment]
See my comment in https://github.com/mavlink/MAVSDK/pull/1090. I used `-H` where `-S` was failing, not sure if that is solved everywhere. `-S` will work everywhere at some point, but it seems to me that `-H` is legacy, and in some cases needed (because it's still much nicer than `mkdir build && cd build && cmake` IMO).

**Comment by julianoes** [comment]
Ok, so the issue might be with cmake 3.5.1 on Ubuntu 16.04.

So in that case it might be correct to use `-H` everywhere until we drop support for 16.04.

**Comment by TSC21** [comment]
> Ok, so the issue might be with cmake 3.5.1 on Ubuntu 16.04.
> 
> So in that case it might be correct to use `-H` everywhere until we drop support for 16.04.

Btw I am using Ubuntu 18.04 and I can't seem to use -S.

**Comment by julianoes** [comment]
Let's leave it as is with `-H`.

**Pull request closed without merging**
