### PR TITLE
api_reference: update for v0.33.0

### PR DESCRIPTION
**Pull request by julianoes**
After this, we also need to update v0.34.0 and develop.

And at some point we need to go through the examples and update it all.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Any new docs need to be added to en/SUMMARY.md and the README in the same folder - e.g. structmavsdk_1_1_mavlink_passthrough_1_1_command_int.md 

Other than that you can just merge. Periodically i use a link checker to validate that the anchor links within the docs were not broken.

**Comment by julianoes** [comment]
Will do, thanks @hamishwillee .

**Comment by hamishwillee** [comment]
Cool. Let me know if you want a new check done after that.

BTW as we add new APIs at some point we should consider if there is additional guide required for some of these.

**Comment by julianoes** [comment]
> BTW as we add new APIs at some point we should consider if there is additional guide required for some of these.

Yes, we should update some of the notes around it.

**Comment by hamishwillee** [comment]
Looks great to me. Merging.

**Pull request merged**
