### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by julianoes**
See commits for details.

### CODE REVIEW

**Comment by julianoes** [comment]
Self merging, let's see if it updates the docs this time.

**Comment by hamishwillee** [comment]
Seems to have worked well. Quick scan I have nothing to add.

**Comment by julianoes** [comment]
Thanks @hamishwillee. Note that Jenkins didn't trigger. I had to manually trigger it.

**Comment by hamishwillee** [comment]
Bugger. Perhaps talk to Daniel.

**Pull request merged**
