### PR TITLE
Update telemetry.md; telemetry.subscribe_all_ok() does not exist

### PR DESCRIPTION
**Pull request by raceking37**
Found a small error in the documentation: telemetry.subscribe_all_ok() doesn't exist, this was probably meant to be the telemetry.subscribe_health_all_ok() method.

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
Thanks! 
@julianoes I'm merging because there doesn't seem to be anything else this can be. More generally, should we be saying what health OK means? I assume it means OK to arm "as far as we know" but it might mean "OK to arm canonically" or something else.

**Comment by julianoes** [comment]
Thanks, makes sense.

There is the flag `health.is_armable()` which tells you whether arming is possible:
https://github.com/mavlink/MAVSDK/blob/849cb9a3c3bd18d21731da3b0c4fe31ca6b9d039/src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h#L410

**Comment by hamishwillee** [comment]
So what does healthy "mean" then in MAVlink terms? Yes I could look it up. I guess I'm hinting we need to be a bit more clear about how the data can be used in the docs.

**Comment by hamishwillee** [comment]
Perhaps replace it with something more meaningful in next revision then?

**Comment by julianoes** [comment]
Perhaps yes.

**Pull request merged**
