### PR TITLE
Make label on front of version v2 say v2 - not main

### PR DESCRIPTION
**Pull request by hamishwillee**
As it is now

image

### CODE REVIEW

**Review by julianoes — APPROVED** [review]
Thanks!

**Comment by hamishwillee** [comment]
Cool. We'll look at moving to Vitepress in the new year.

**Comment by julianoes** [comment]
I'd also like to include the Python docs: http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/

**Comment by hamishwillee** [comment]
You mean include them as part of the single docs package? Python docs are generated with doxygen or something else? 

We need to think about this. The hand crafted C docs parser I created is a little flakey. We might be better off looking at using doxygen for generating all reference docs. If we want to import within Vitepress to have a central home, we can possibly then do that by importing the HTML. It looks fairly flexible so this might well be possible. Needs more investigation.

**Comment by julianoes** [comment]
Sure, we need to figure out how to generate the files for it.

**Comment by hamishwillee** [comment]
For Python maybe https://niklasrosenstein.github.io/pydoc-markdown/ - I used this for generating the libmav python docs from some pretend Python classes (see https://github.com/Auterion/libmav-python/blob/main/docs/build/docs/content/libmav.md).
What I like about this is that it supports many input/output formats so you can probably get it to work quite well on the sources you already have.

But that still leaves C++. My parser is not robust enough, so we need a better way to get markdown for that.

**Pull request merged**
